### ISSUE TITLE
Facebook share shows disclaimer meta-data

### ISSUE THREAD

**Issue by badtesting** [Hphenix/hdd#16]
![justeat-facebook-share-desktop](https://cloud.githubusercontent.com/assets/1880170/5939520/0fa6d4d2-a6ca-11e4-8a81-6828cb3d35a2.png)

**Comment by Hphenix** [comment]
Hey Shak
We're working on the metadata
Just making sure all the Facebook accounts you're using for testing are
private, correct?
thanks!

On Wed, Jan 28, 2015 at 9:45 AM, BadTesting notifications@github.com
wrote:

> [image: justeat-facebook-share-desktop]
> https://cloud.githubusercontent.com/assets/1880170/5939520/0fa6d4d2-a6ca-11e4-8a81-6828cb3d35a2.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Hphenix/hdd/issues/16.

## 

HEATHER PHENIX  |  PRODUCER  |  JAM3
T: 416.531.5263   M: 647.213.6978
325 Adelaide St. W  Toronto  Ontario  M5V 1P8

A MEMBER OF THE FWA HALL OF FAME
Follow us:  Twitter.com/jam3

**Comment by badtesting** [comment]
Yeah! I forgot to mention this... it's a private 'test' account, not my actual facebook account.  So that's the reason for the fake 'Scott Smith' name.... and I immediately deleted the post's also. So they are no longer there. Thanks!

**Comment by Hphenix** [comment]
ok great!
thanks Shak.

On Wed, Jan 28, 2015 at 3:29 PM, BadTesting notifications@github.com
wrote:

> Yeah! I forgot to mention this... it's a private 'test' account, not my
> actual facebook account. So that's the reason for the fake 'Scott Smith'
> name.... and I immediately deleted the post's also. So they are no longer
> there. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Hphenix/hdd/issues/16#issuecomment-71909735.

## 

HEATHER PHENIX  |  PRODUCER  |  JAM3
T: 416.531.5263   M: 647.213.6978
325 Adelaide St. W  Toronto  Ontario  M5V 1P8

A MEMBER OF THE FWA HALL OF FAME
Follow us:  Twitter.com/jam3

**Comment by badtesting** [comment]
verified fixed
